name: cvamd
ckpt_dir: ckpt

dataset:
  proto: ImLabel
  label:
    root: data/CLASS/CVAMD
    file: label.tok

  image:
    root: data/CLASS/CVAMD
    file: image.tok
    image_path: /scratch/users/tsounack/mimic-cxr-images-512
    load_memory: False
    resize: 256
    crop: 224
    ext: .jpg

model:
  proto: ICCV

  classifier:
    proto: Classifier
    input_size: 768
    num_classes: 27
    dropout: 0.

  loss:
    proto: WeightedBCEWithLogitsLoss

trainor:
  optimizer: Adam
  optim_params:
    lr: 0.00005
    weight_decay: 5e-4
  batch_size: 32
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.5
    patience: 1
    min_lr: 0.000001
    threshold: 0.01
    threshold_mode: abs
  epochs: 99
  early_stop: 3
  eval_start: 0
  early_stop_metric: mapaccuracy


validator:
  batch_size: 16
  metrics: [ap, mapaccuracy]
  splits: [validate]

ensemblor:
  batch_size: 16
  metrics: [ap, mapaccuracy]
  splits: [validate, test]
  mode: all